### ISSUE TITLE
Reorganize git

### ISSUE THREAD

**Issue by wesg52** [CornellDataScience/IntSys-Sentiment-Summary#7]
We need to figure out the best way to organize our code. We probably want a different folder for each model variant with the training scripts, a utilities folder for preprocessing scripts, and a notebooks or experiments folder.

**Comment by jz393** [comment]
I created my own branch a while ago, we could each have our own branches? Not sure if it's the most optimal way

**Comment by garnav** [comment]
Yeah, I made my own branch as well to try CCA stuff. How about the organization scheme they suggest on this: [https://drivendata.github.io/cookiecutter-data-science/](https://drivendata.github.io/cookiecutter-data-science/)
